init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.substring(1))"
      }
      else
      {
        Update-AppveyorBuild -Version "$(((nuget list libphonenumber-csharp -Source https://api.nuget.org/v3/index.json | findstr "libphonenumber-csharp[^.-]") -split ' ')[1])-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
image: Visual Studio 2017
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: tHOHVQ3dw2NqnKUW3EQbBIe+ytxPnGjJ13psSpwYhxbWlvtl6CKVmqigzfCR2nSc
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
before_build:
  - ps: xcopy "C:\Program Files (x86)\MSBuild\Microsoft\Portable" "C:\Program Files\dotnet\sdk\$(dotnet --version)\Microsoft\Portable\" /S /E
  - dotnet restore csharp -s https://api.nuget.org/v3/index.json
  - choco install opencover.portable
  - choco install codecov
  - ps: Get-ChildItem -r .\resources\geocoding\ -File | Rename-Item -NewName { 'prod_'+$_.Name+'_'+$_.Directory.Name -replace '.txt',''}
  - ps: Get-ChildItem -r .\resources\geocoding\ -File | Move-Item -Destination .\csharp\PhoneNumbers\res\
build_script:
  - cmd: dotnet pack -c Release csharp\PhoneNumbers
test_script:
  - OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test csharp\PhoneNumbers.Test\PhoneNumbers.Test.csproj" -filter:"+[PhoneNumbers]* -[PhoneNumbers.Test]*" -excludebyattribute:*.CompilerGenerated*^ -oldStyle
  - codecov -f results.xml
artifacts:
  - path: csharp\PhoneNumbers\bin\Release\libphonenumber-csharp.*
nuget:
  account_feed: true
deploy:
  - provider: NuGet
    on:
      appveyor_repo_tag: true
    api_key:
      secure: MCwHTCbHS1/wQ/DZbGrUuJrWBKBm6e6TYeR0QCHIg9QlXBQQicwtquGYYGu5hK4Y
